#ifndef TOKENTYPE_H
#define TOKENTYPE_H

#include <stdlib.h>

typedef enum {
    // basic types and const
    TOKEN_VOID,
    TOKEN_CONST,
    TOKEN_BOOL,

    // int type
    TOKEN_INT8,
    TOKEN_INT16,
    TOKEN_INT32,
    TOKEN_INT64,
    TOKEN_UINT8,
    TOKEN_UINT16,
    TOKEN_UINT32,
    TOKEN_UINT64,

    // float type
    TOKEN_FLOAT32,
    TOKEN_FLOAT64,

    // char type
    TOKEN_CHAR,
    TOKEN_UCHAR,

    // string literal
    TOKEN_STRING_LITERAL,

    // Declaratins
    TOKEN_FUNC,
    TOKEN_TYPEDEF,
    TOKEN_STRUCT,

    // Control flow
    TOKEN_RETURN,
    TOKEN_IF,
    TOKEN_ELSE,
    TOKEN_FOR,
    TOKEN_WHILE,
    TOKEN_BREAK,
    TOKEN_CONTINUE,

    // Boolean literals
    TOKEN_TRUE,
    TOKEN_FALSE,
	TOKEN_NUMBER,
	TOKEN_IDENTIFIER,

	// SYMBOLS
	TOKEN_LPAREN,
	TOKEN_RPAREN,
	TOKEN_LBRACE,
	TOKEN_RBRACE,
	TOKEN_LBRACK,
	TOKEN_RBRACK,
	TOKEN_SEMICOLON,
	TOKEN_DOT,
	TOKEN_COMMA,
    TOKEN_TILDE,
    TOKEN_ARROW,
    TOKEN_MINUS_EQUAL,
    TOKEN_DECREMENT,
    TOKEN_MINUS,
    TOKEN_PLUS_EQUAL,
    TOKEN_INCREMENT,
    TOKEN_PLUS,
    TOKEN_EXCL_EQUAL,
    TOKEN_EXCL,
    TOKEN_ASTERISK_EQUAL,
    TOKEN_ASTERISK,
    TOKEN_AMPERS_AMPERS,
    TOKEN_AMPERS_EQUAL,
    TOKEN_AMPERS,
    TOKEN_SLASH_EQUAL,
    TOKEN_SLASH,
    TOKEN_PERC_EQUAL,
    TOKEN_PERC,
    TOKEN_LESS_LESS_EQUAL,
    TOKEN_LESS_LESS,
    TOKEN_LESS_EQUAL,
    TOKEN_LESS,
    TOKEN_MORE_MORE_EQUAL,
    TOKEN_MORE_MORE,
    TOKEN_MORE_EQUAL,
    TOKEN_MORE,
    TOKEN_EQUAL_EQUAL,
    TOKEN_EQUAL,
    TOKEN_CARET_EQUAL,
    TOKEN_CARET,
    TOKEN_PIPE_EQUAL,
    TOKEN_PIPE_PIPE,
    TOKEN_PIPE
} TokenType;

#endif